apiVersion: v1
kind: Service
metadata:
    name: "main-2c79"
    labels:
        app: "main-2c79"
spec:
    type: LoadBalancer
    ports:
    - port: 8500
      targetPort: 8500
      protocol: TCP
      name: http
    selector:
        app: "main-2c79"