on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: artio.azurecr.io
        username: ${{ secrets.acr_artio_username }}
        password: ${{ secrets.acr_artio_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t artio.azurecr.io/main:${{ github.sha }}
        docker push artio.azurecr.io/main:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_main_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep main4c54 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace main4c54`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: main4c54
        container-registry-url: artio.azurecr.io
        container-registry-username: ${{ secrets.acr_artio_username }}
        container-registry-password: ${{ secrets.acr_artio_password }}
        secret-name: maindockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: main4c54
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          artio.azurecr.io/main:${{ github.sha }}
        imagepullsecrets: |
          maindockerauth